.github/workflows/build-docker.yml
.github/workflows/test.yml

I've basically just copy-pasted this from `alexandria`.

WEB-3330: Adding some slack notifications to robles builds

---

app/lib/parser/publish.rb
app/models/book.rb
app/models/concerns/image_attachable.rb

3 extra images, a video URL, domains and categories.
None of them is marked as required.

WEB-3423: Adding extra metadata

---

app/lib/image_provider/markdown_image_extractor.rb
app/lib/image_provider/provider.rb

- Adding support for the `free` attribute on chapters

v1.0.3: 🐌 Slime

---

app/lib/linting/image/attachable.rb
app/lib/linting/linter.rb
app/lib/linting/markdown/book.rb
app/lib/linting/markdown/chapter.rb
app/lib/linting/markdown/renderable.rb
app/lib/linting/markdown/section.rb
app/lib/linting/markdown_linter.rb

This didn't actually solve the problem I was trying to solve, but I
think it might be useful in future, so I'll leave it in.

WEB-3514: Adding a framework for linting markdown content

---

app/lib/parser/publish.rb
app/models/book.rb

WEB-3566 & WEB-3570: Adding support for new display attributes

---

app/commands/robles_cli.rb
app/lib/parser/publish.rb
app/models/book.rb

- Adding support for an external manifest file

v1.0.6: 🐌ed It

---

app/server/robles_server.rb
app/server/views/_index_table_of_contents.html.erb
app/server/views/chapter.html.erb
app/server/views/index.html.erb
app/server/views/styles/application.scss

Mainly adding styling to index page

WEB-3580: More styling for local preview

---

app/lib/linting/metadata/publish_attributes.rb
app/lib/parser/publish.rb
app/models/book.rb

- `forum_url`
- `short_description`
- `pages`
- `recommended_skus`
Made only `short_description` required.

WEB-3586: Adding support for the new attributes

---

app/lib/parser/publish.rb

- Switching out the markdown engine for CommonMark
- Adding local preview via bin/robles serve
- Adding new attributes
- Adding support for vend.yaml
- Making description field support markdown

v1.0.7: 🐌 Polish

---

app/models/episode.rb

Not sure, but I must have forgotten it

WEB-3917: Adding authors_notes to what gets sent to betamax

---

app/lib/renderer/image_attributes.rb

This will also need support adding in carolus

WEB-3968: Adding support to generate float left and right image classes

---

app/commands/video_cli.rb
app/lib/snapshotter/slides.rb

Default now puts it inside artwork

WEB-3995: Allowing custom slide export location

---

app/commands/book_cli.rb
app/commands/robles_cli.rb
app/commands/video_cli.rb
bin/robles

This will cause staging to always report success, but I think that's ok
It will prevent team members getting emails and red ticks on things
they don't understand.

WEB-3978: Should make staging fail silently from now on

---

app/lib/linting/vend_linter.rb
app/server/robles_book_server.rb
app/server/robles_video_server.rb

- Allowing images with `.` in filename

v2.1.1: Colin the 🐛 Cake

---

.github/dependabot.yaml
.github/workflows/build-docker.yml
.github/workflows/test.yml
Gemfile
Gemfile.lock

WEB-4144: Enabling multi-arch builds

---

app/server/public/javascript/highlight.pack.js

- Adds CSS, SQL, markdown & Ruby to supported languages

WEB-4198 & WEB-4203: Adds syntax highlighting

---

README.md
app/server/views/styles/diagrams.scss

- As per https://github.com/razeware/carolus/commit/7efac1daeb135ce95f7db066d9e164f092a24c77

WEB-4313: Adding dark mode to local preview

---

app/lib/image_provider/directory_extractor.rb
app/models/gallery_image.rb

And names are just `-` separated.
Feel free to merge if this is done, or you can add to it if you want.

WEB-4353: Switching to using directories for categorisation

---

app/lib/image_provider/markdown_image_extractor.rb
app/lib/linting/image/markdown.rb
app/lib/renderer/image_attributes.rb
app/lib/renderer/rw_markdown_renderer.rb

Also shows the error in the local preview.

WEB-4443: Adding linting to ensure that images include width

---

app/lib/parser/video_course.rb

Turns out, it also fails linting, so that's nice

WEB-4472: Fail video upload with exception if script or subtitles missing

---

app/lib/renderer/episode.rb

Hi @sammyd! I got started with this. Your review will be much appreciated and will help me know if I am on the right track.
The remaining part has to do with storing the text in the transcript field.

WEB-5072: Use caption file as transcripts

---

app/server/views/videos/episode_slide.html.erb

WEB-5184: Removing the rw.com logo from the slide

---

app/lib/renderer/episode.rb
app/lib/renderer/markdown_renderable.rb
app/lib/renderer/part.rb
app/lib/renderer/video_course.rb
app/lib/snapshotter/slides.rb
app/server/robles_video_server.rb

Also increase the timeout for the snapshotter to 15s, so that it should
have a chance to complete rendering the slide before it gives up.

WEB-5131: Only generate transcripts when needed for local web server

---

Gemfile
Gemfile.lock

WEB-5204: Fixes gem

---

.editorconfig

This PR adds the `.editorconfig` file to the root of robles' repo.
* N/A
* N/A

WEB-5196: Add EditorConfig file for consistent coding styles

---

app/commands/video_cli.rb
app/lib/linting/file_existence_checker.rb
app/lib/parser/assessment_metadata.rb
app/lib/parser/video_course.rb
app/lib/parser/video_metadata.rb
app/lib/renderer/assessment.rb
app/lib/renderer/assessment/choice.rb
app/lib/renderer/assessment/question.rb
app/lib/renderer/episode.rb
app/lib/renderer/part.rb
app/lib/renderer/video.rb
app/models/assessment.rb
app/models/assessment/choice.rb
app/models/assessment/question.rb
app/models/assessment/quiz.rb
app/models/video.rb
app/server/robles_video_server.rb
app/server/views/videos/_index_table_of_contents.html.erb
app/server/views/videos/_table_of_contents.html.erb
app/server/views/videos/assessment.html.erb
app/server/views/videos/episode_slide.html.erb
app/server/views/videos/episode_transcript.html.erb

- Renamed episode to video
- Built assessment parser
- Adding local preview
- Adding ref parameter
Might need to take a look at adding linter support.

WEB-5947: Adding support for assessments in robles

---

.github/workflows/build-docker.yml
.github/workflows/test.yml

- Fixing secrets upload and linting messaging

v2.3.3: Con🦭er

---

app/models/video_course.rb
app/server/robles_video_server.rb
app/server/views/styles/components/slide.scss

- Adds it as an approved domain
- Updates naming in slide generator
- Removes an unused method

WEB-6220: Adds ProGro to robles

---

app/lib/renderer/video.rb

WEB-6411: Accidentally overwriting transcripts with captions

---

app/lib/runner/ci.rb

WEB-6415: Add default module file location

---

app/lib/util/slack_notifiable.rb

WEB-6415: Missing method error fix

---

app/lib/parser/lesson_metadata.rb
app/lib/snapshotter/content_module_slides.rb
app/lib/snapshotter/video_course_slides.rb
app/models/lesson.rb

It's possible that it's because we don't use LOs yet? Not sure. But we defo need description.

WEB-6520: Missing description and learning objective fields from lesson

---

app/lib/image_provider/provider.rb
app/lib/renderer/rw_markdown_renderer.rb
app/lib/runner/base.rb

I just wrote down what Sam told me....

WEB-6548: We mostly don't care about widths

---

app/lib/renderer/lesson.rb
app/models/lesson.rb

WEB-6534: Make lesson ref mandatory

---

app/models/lessons_validator.rb

I removed it before cos I thought it meant something else. turns out i was just being a bit dumb.

WEB-6569: Lesson title in linter

---

app/lib/image_provider/provider.rb
app/lib/runner/base.rb

Also set a default of true, so we'd get a different error in future.

WEB-6582: Missed a reference to the new width_required argument

---

app/server/local_image_provider.rb
app/server/robles_book_server.rb
app/server/robles_content_module_server.rb

WEB-6754: Fixing images in local preview

---

bin/robles

v2.4.2: 🪰 in the ointment

---

app/server/public/javascript/highlight.pack.js
app/server/public/javascript/timestamps.js

WEB-7281: Tidying timestamps into just minutes and seconds

---

app/lib/parser/text_metadata.rb
app/models/text.rb
app/server/public/javascript/highlight.pack.js
app/server/public/javascript/timestamps.js

WEB-7274: Makes Text descriptions markdownable

---

.github/workflows/build-docker.yml

- Trying to get semver to work correctly

v2.5.4: 🥚head

---

Gemfile
Gemfile.lock

- Attempting to fix protobuf musl issue

v2.5.5: over-🥚ed

---

app/models/content_module.rb
app/models/video_course.rb
app/server/views/styles/abstracts/colors.scss
app/server/views/styles/components/slide.scss

- Adds AI as an allowed domain
- Adds colour to slide:

WEB-7288: Add AI domain to robles
