app/lib/renderer/rw_markdown_renderer.rb
I have a feeling that this will also remove the TOC anchors, but I'm
pretty sure that we weren't using them anyway.
=> WEB-3337: <h1> Tags are now ignored

app/lib/linting/metadata/publish_attributes.rb, app/lib/parser/publish.rb, app/models/book.rb
This is now a required attribute in publish.yaml. It will be sent to
alexandria as materials_url.
=> WEB-3251: Adding support for a materials_url read from the metadata

app/lib/image_provider/extractor.rb, app/lib/linting/image/attachable.rb, app/lib/linting/image/book.rb, app/lib/linting/image/chapter.rb, app/lib/linting/image/section.rb, app/lib/linting/image_linter.rb, app/lib/linting/metadata/publish_attributes.rb, app/lib/parser/book_segments.rb, app/lib/parser/publish.rb, app/lib/renderer/book.rb, app/lib/renderer/chapter.rb, app/lib/renderer/image_attachable.rb, app/lib/renderer/markdown_file_renderer.rb, app/lib/renderer/markdown_renderable.rb, app/lib/renderer/markdown_string_renderer.rb, app/lib/renderer/section.rb, app/lib/runner/base.rb, app/models/book.rb, app/models/chapter.rb, app/models/concerns/image_attachable.rb, app/models/concerns/markdown_renderable.rb, app/models/section.rb
This adds the following fields:
```
"cover_image_url": "<string (full url)>",
"version_description": "<string (ex. 'Eighth Edition')>",
"professional": "<boolean>",
"difficulty": "<string (beginner/intermediate/advanced)>",
"platform": "<string>",
"language": "<string>",
"editor": "<string>",
"who_is_this_for": "<string with HTML>",
"covered_concepts": "<string with HTML>"
```
In order to support this, the renderer has been extended to allow individual attributes to be marked as containing markdown, in addition to them containing a path to a markdown file. It's also now possible to have more than one of these attributes on a model object.
Model objects can now also have image attributes, which will be uploaded to the CDN in the same way. currently we only vend the original image size to …
=> WEB-3417: Adding new fields to robles metadata

app/lib/image_provider/markdown_image_extractor.rb, app/lib/image_provider/provider.rb
./images/image.png is now interpreted the same as images/image.png
=> WEB-3425: Normalise image paths

app/lib/parser/chapter_metadata.rb, app/models/chapter.rb
- If the attribute is missing, it should default to `false`
=> WEB-3426: Adding the free attribute to chapter metadata

app/lib/linting/linter.rb, app/lib/parser/error.rb, app/lib/parser/markdown_metadata.rb
We don't verify the metadata, but we do now add some location info
so that it's possible to tell which file has the problem—rather than
having to search through every single chapter to find the extra space
in the indentation...
=> WEB-3513: Parsing errors in chapter metadata are now labelled

app/lib/parser/book_segments.rb, app/models/chapter.rb, app/models/concerns/auto_numberable.rb, app/models/section.rb
Instead of providing a display number string for each chapter, you can instead put the word `auto`. This will work out the appropriate chapter number from the previously numbered chapter.
It will try to parse each chapter number string as an integer. This allows starting the numbered chapters with an offset.
=> WEB-3565: Adding support for "auto" numbered chapters and sections

app/commands/robles_cli.rb, app/lib/parser/publish.rb
This was requested by the cookbook team so that they can auto-generate
the manifest file from the directory structure. It first looks for a
manifest_file attribute in publish.yaml, before falling back to using
the publish.yaml itself.
I don't expect that this will be useful outside cookbooks.
=> WEB-3583: Allow book "segments" to be specified in a manifest file

Gemfile, Gemfile.lock, app/lib/image_provider/markdown_image_extractor.rb, app/lib/renderer/markdown_file_renderer.rb, app/lib/renderer/markdown_string_renderer.rb, app/lib/renderer/rw_markdown_renderer.rb
I discovered that codex actually uses CommonMark as a standard, which explains why we're seeing discrepancies between the PDF and the site. This switches it—I think it should fix some issues, and hopefully not create any regressions.
=> WEB-3588: Switching the markdown engine

app/lib/linting/metadata/publish_attributes.rb, app/models/book.rb, app/server/views/index.html.erb
This means it'll have to be renamed description_md in publish.yaml, but
I think that's a sensible thing to do to ensure that it is obvious that
it accepts markdown.
=> WEB-3617: Making the description field markdown compatible

app/lib/parser/publish.rb, app/models/book.rb
I've reviewed publish.yaml in bkk and checked that we have all the
attributes covered. We now do =)
=> WEB-3637: Adding amazon_url and ISBN as book attributes

app/lib/parser/publish.rb, app/models/book.rb
- Adding support for amazon_url and ISBN
=> v1.0.8: Hit the 🐌 on the head

app/commands/robles_cli.rb
This adds an IRB console within the context of robles. It also adds a
`book` variable as a convenience for working with the publisher.
=> Add an irb binding console command

app/commands/robles_cli.rb, app/lib/image_provider/extractor.rb, app/lib/image_provider/markdown_image_extractor.rb, app/lib/image_provider/provider.rb, app/lib/parser/publish.rb, app/lib/renderer/image_attachable.rb, app/lib/renderer/image_attributes.rb, app/models/book.rb, app/models/concerns/image_attachable.rb, app/models/image.rb, app/models/image_representation.rb
This adds the new image types that are required for display across
the site. It also changes the upload API, where image URLs are now
provided as an array of objects, each with `url` and `variant` keys.
=> WEB-3823: Allows specification of image variants as attachments

app/lib/linting/linter.rb, app/lib/linting/metadata/edition_reference.rb, app/lib/linting/vend_linter.rb, app/lib/parser/vend.rb
This is intended as a check to ensure that vend.yaml is reviewed before
a new release can be published.
=> WEB-3827: Adding a new edition attribute to vend.yaml

Gemfile, Gemfile.lock, app/server/robles_server.rb, app/server/views/index.html.erb
This is because of the image variants changes I made—I forgot to fix the bit that approximates it for the local server.
Rather that use an `ImageRepresentation` I chose to use an `OpenStruct`, since I only have a key-value required. This would fail the validation of an IR.
I'll do a release of this as soon as it's reviewed so the book teams aren't held up.
=> WEB-3836: Fixing issue with local preview

app/lib/parser/publish.rb, app/models/book.rb
This adds the ability to read a `deprecated` flag attribute in
publish.yml. This flag will be used to retire a book so that it's no
longer available to subscribers, but still available to purchases. The
book will also not show up in search results.
=> WEB-3932 Add deprecated flag

app/lib/linting/vend_linter.rb
Missed this when renaming to add support for videos
=> WEB-3969: Updating a lint class reference

app/server/robles_server.rb
- Add support for serving images with a `jpeg` extension
- Prevents caching of all files by browser. I think.
=> WEB-3969: Improvements to local server

app/lib/linting/vend_linter.rb
This will allow team members to preview the published versions before
the version check is completed
=> WEB-4019: Disabling the vend.yaml version check

app/server/robles_book_server.rb, app/server/robles_video_server.rb
This was causing the slide generator to fail with @1.5x.png files
=> WEB-4049: Adding support for images with more than one . in their name

app/lib/parser/book_segments.rb, app/lib/renderer/markdown_file_renderer.rb, app/models/chapter.rb, app/models/concerns/markdown_renderable.rb, app/server/views/books/chapter.html.erb, app/server/views/styles/components/content.scss
Adds support for two new page types:
- `dedications`
- `team-bios`
As part of this, the following has changed with the markdown rendering engine:
- Allow specifying a class for a wrapper `<div>` on the markdown attribute
- Process the special pagesetting commands on the team bios page
@jellodiil A few small changes need to be made to the repos, but not that much:
- Dedications and team bios chapters need moving after the first section intro
- The Dedications title needs to be `<h1>` so that it gets ignored
- The team-bios subheadings (for each department) need to be `<h2>`
- The images in the team bios page need to be `bordered`
- Both pages need the standard chapter metadata adding at the top
This should still render identically in Deckle
=> WEB-4174: Adding support for dedications and team bios

app/lib/image_provider/book_extractor.rb, app/lib/image_provider/video_course_extractor.rb
Instead of using a sku or shortcode, this replaces it with a hexdigest
representation. This should help mitigate adblocking software from
blocking our images.
=> WEB-4186 Use a hexdigest in image urls

app/lib/parser/publish.rb, app/models/book.rb
I couldn't find anywhere else where the artwork is mentioned?
I added `original`, `w180`, `w300` and `w594` as the image sizes as per the ticket (and copying the other images).
=> WEB-4151: Updating gallery_image to email_mockup_image

app/lib/cli/output_formatter.rb, app/lib/linting/book_linter.rb, app/lib/linting/markdown/renderable.rb, app/lib/linting/markdown/word_counter.rb, app/server/robles_book_server.rb, app/server/views/books/_index_table_of_contents.html.erb, app/server/views/books/chapter.html.erb, app/server/views/styles/application.scss, app/server/views/styles/objects/messages.scss, docker-compose.yml
Adding a word counter for markdown that counts words that aren't in code blocks. It's not perfect—there are times when it joins words together unnecessarily, and times where it splits them up. However, I think that it's accurate enough for the guidance. As long as the teams use this metric for their word counts then it doesn't matter.
This adds listing warnings for book chapters that are over the word limit (4000):
These should be just warnings, and shouldn't cause lint to fail. I don't think.
Also, on the book overview page:
And the chapter page itself:
When it doesn't exceed the word limit, the chapter page just shows the count:
=> WEB-4314: Word count + warnings into robles

app/lib/renderer/markdown_file_renderer.rb, app/lib/renderer/markdown_timestamper.rb
Adding this to a line in markdown will cause the entire line to be
ignored by the markdown processor. It can be anywhere on a line.
=> WEB-4471: Adding $[//] as comment syntax in markdown files

app/lib/linting/image/attachable.rb, app/lib/linting/image/markdown.rb
Basically, some files we check both attached images and markdown images
which means that we use both the Markdown and the Attachable modules.
Trouble is, they shared some method naming, which means that we
overwrote one with the other.
This gives the similar methods in the two modules unique names, so they
no longer clash.
Also updates the error message to be more helpful.
=> WEB-4523: Fixes a problem with clashing method names

app/server/views/styles/components/slide.scss
Some video courses have Very Long Episode Titles.
They now break onto more than one line.
=> WEB-5461: Breaks episode titles to several lines

app/lib/ci/linting_reporter.rb, app/lib/repo_management/secrets.rb
Which should allow secrets to be uploaded again, and linting to be reported
=> WEB-6165: Removes faraday retry middleware

app/commands/content_module_cli.rb
=> WEB-6415: Accept module secrets

app/commands/content_module_cli.rb, app/commands/video_cli.rb, app/lib/parser/lesson_metadata.rb, app/lib/snapshotter/content_module_slides.rb, app/lib/snapshotter/slides.rb, app/lib/snapshotter/video_course_slides.rb, app/models/lesson.rb, app/server/robles_content_module_server.rb, app/server/views/content_modules/_index_table_of_contents.html.erb, app/server/views/content_modules/_table_of_contents.html.erb, app/server/views/content_modules/segment_slide.html.erb
- Design didn't have the correct elements
- Server paths didn't include lessons, so not all slides were accessible
- Generator needs to support different settings for videos vs modules
- Default output location is different
- Ref wasn't being parsed correctly
=> WEB-6519: Fix slides

app/lib/parser/video_metadata.rb, app/models/video.rb
Allows it to be blank, just the ID, or the vimeo URL.
=> WEB-6559: Extract the vimeo_id from metadata, add to model, and push

app/models/lessons_validator.rb
=> WEB-6564: Complain at non-unique titles

app/server/views/content_modules/segment_slide.html.erb, app/server/views/styles/components/slide.scss
- Updates video stuff to match carolus
- Adds changes for modular stuff
(I have no idea how to test this, so probably will need to check on staging)
=> WEB-6573: Matches slide generator to carolus

app/lib/parser/lesson_metadata.rb, app/models/lesson.rb
- Update references to raywenderlich.com to Kodeco Inc.
- WEB-6734: Update ruby to 3.3
=> WEB-6625: Add free attribute to Lesson

app/lib/linting/content_module_linter.rb, app/lib/linting/image/content_module.rb, app/lib/linting/image/lesson.rb, app/lib/linting/image/markdown.rb, app/lib/linting/image/segment.rb, app/lib/linting/image_linter.rb, app/models/lesson.rb, app/models/segments_validator.rb
- Verifying image existence
- Uniqueness of refs and titles for lessons and segments
=> WEB-6757: Fixing some listing problems

app/lib/util/slack_notifiable.rb
Adds one for content modules, and switches from raze face style to kodeco
=> WEB-6568: Updating slack images in robles

.github/workflows/build-docker.yml, app/lib/parser/content_module.rb, app/lib/parser/lesson_metadata.rb, app/lib/runner/base.rb, app/models/content_module.rb, app/models/lesson.rb
This introduces info and study modules. Study is the default, info has some different types.
=> WEB-6880: Adding module_type and program_shortcode to module + lesson

app/server/views/styles/components/modular.scss
- Updates the positioning of timestamps now they are shorter
- Fixes blockquotes and ul,ol and timestamps nonsense
=> WEB-7287: Transcript timestamp styling

app/server/views/styles/components/modular.scss
=> WEB-7289: Fixing TOC numbering width
